# Generated by Django 3.1.4 on 2021-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
