# Generated by Django 3.1.4 on 2020-12-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20201217_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(default=True, max_length=500),
        ),
    ]
