# Generated by Django 3.1.4 on 2021-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210107_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
