# Generated by Django 3.1.4 on 2020-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=True)),
                ('question', models.TextField(default=True, max_length=500)),
                ('option1', models.CharField(default=True, max_length=300)),
                ('option2', models.CharField(default=True, max_length=300)),
                ('option3', models.CharField(default=True, max_length=300)),
                ('option4', models.CharField(default=True, max_length=300)),
                ('answer', models.CharField(default=True, max_length=300)),
            ],
        ),
    ]
