# Generated by Django 3.1.4 on 2020-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20201228_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='prophoto.png', null=True, upload_to=''),
        ),
    ]
